server:
  port: 9001
spring:
  application:
    name: consumer
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/,http://localhost:8762/eureka/
## zuul配置
# zuul默认配置：默认情况下，Zuul会代理所有注册到Eureka Server的微服务，并且Zuul的路由规则如下：http://ZUUL_HOST:ZUUL_PORT/微服务在Eureka上的serviceId/**会被转发到serviceId对应的微服务。
zuul:
  ## zuul自定义配置
  routes:
    ## api-a为路由别名，无其他意义，多个时保证不重复即可
    api-a:
      ## path为请求路由地址，即http://localhost:9001/api-producer/**
      path: /api-producer/**
      ## service-id为映射的服务名称，即请求http://localhost:9001/api-producer/**，会映射到demo-api服务中
      service-id: demo-api
feign:
  hystrix:
    ## 开启feign的降级功能，默认是false
    enabled: true
management:
  endpoints:
    web:
      exposure:
        ## management.endpoints.web.exposure.include这个是用来暴露 endpoints 的。由于 endpoints 中会包含很多敏感信息，除了 health 和 info 两个支持 web 访问外，其他的默认不支持 web 访问。
        include: ["health","info","hystrix.stream"]