server:
  port: 9001
spring:
  application:
    name: consumer
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/,http://localhost:8762/eureka/
## zuul配置
zuul:
  routes:
    ## api-a为路由别名，无其他意义，多个时保证不重复即可
    api-a:
      ## path为请求路由地址，即http://localhost:9001/api-producer/**
      path: /api-producer/**
      ## service-id为映射的服务名称，即请求http://localhost:9001/api-producer/**，会映射到demo-api服务中
      service-id: demo-api
feign:
  hystrix:
    ## 开启feign的降级功能，默认是false
    enabled: true