server:
  port: 9001
spring:
  application:
    name: consumer
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/,http://localhost:8762/eureka/
## zuul\u914D\u7F6E
zuul:
  routes:
    ## api-a \u4E3A\u8DEF\u7531\u522B\u540D\uFF0C\u65E0\u5176\u4ED6\u610F\u4E49\uFF0C\u591A\u4E2A\u65F6\u4FDD\u8BC1\u4E0D\u91CD\u590D\u5373\u53EF
    api-a:
      ## path \u4E3A\u8BF7\u6C42\u8DEF\u7531\u5730\u5740\uFF0C\u5373http://localhost:9001/api-producer/**
      path: /api-producer/**
      ## service-id \u4E3A\u6620\u5C04\u7684\u670D\u52A1\u540D\u79F0\uFF0C\u5373\u8BF7\u6C42http://localhost:9001/api-producer/**\uFF0C\u4F1A\u6620\u5C04\u5230demo-api\u670D\u52A1\u4E2D
      service-id: demo-api