server:
  port: 8002
spring:
  application:
    ## \u5BF9\u5E94\u914D\u7F6E\u6587\u4EF6\u7684{application}\u90E8\u5206
    name: jerry-config
management:
  endpoints:
    web:
      exposure:
        include: refresh
eureka:
  client:
    service-url:
      # Eureka\u6CE8\u518C\u4E2D\u5FC3\u7684\u5730\u5740\uFF0C\u591A\u4E2A\u4F7F\u7528\u82F1\u6587\u9017\u53F7\u5206\u9694
      defaultZone: http://localhost:8761/eureka/,http://localhost:8762/eureka/