server:
  port: 8002
spring:
  application:
    ## 对应配置文件的{application}部分
    name: jerry-config
management:
  endpoints:
    web:
      exposure:
        include: refresh
eureka:
  client:
    service-url:
      ## Eureka注册中心的地址，多个使用英文逗号分隔
      defaultZone: http://localhost:8761/eureka/,http://localhost:8762/eureka/