server:
  port: 8181
spring:
  application:
    # 指定注册到eureka server上的服务名称
    name: demo-api
eureka:
  client:
    service-url:
      # Eureka注册中心的地址，多个使用英文逗号分隔
      defaultZone: http://localhost:8761/eureka/,http://localhost:8762/eureka/
