server:
  port: 8001
spring:
  application:
    name: spring-cloud-config-server
  cloud:
    config:
      server:
        git:
          # 配置git仓库的地址
          uri: http://git.liuniukeji.com/Java_EE/config/
          # git仓库地址下的相对地址，可以配置多个，用,分割。
          search-paths: jerry
          # git仓库的账号
          username: lijie
          # git仓库的密码
          password: a1234567
eureka:
  client:
    service-url:
      # Eureka注册中心的地址，多个使用英文逗号分隔
      defaultZone: http://localhost:8761/eureka/,http://localhost:8762/eureka/